get:
  tags:
  - System
  summary: Get configs
  description: |
    Get existing configs by search parameters

    **Auth:** Requires valid admin token with one of the following permissions:
    - `get_configs_surveys`
    - `update_configs_surveys`
    - `delete_configs_surveys`
    - `all_configs_surveys`
  security:
    - bearerAuth: []
  parameters:
    - name: type
      in: query
      description: config type
      required: false
      style: form
      explode: false
      schema:
        type: string
  responses:
    200:
      description: Success
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../../schemas/application/Config.yaml"
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error
post:
  tags:
  - System
  summary: Create config
  description: |
    Creates config record

    **Auth:** Requires valid admin token with `update_configs_surveys` or `all_configs_surveys` permission
  security:
    - bearerAuth: []
  requestBody:
    description: New config content
    content:
      application/json:
        schema:
          $ref: "../../schemas/application/Config.yaml"
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error