openapi: 3.0.3
info:
  title: Rokwire Surveys Building Block API
  description: Surveys Building Block API Documentation
  version: 1.11.0
servers:
  - url: 'https://api.rokwire.illinois.edu/surveys'
    description: Production server
  - url: 'https://api-test.rokwire.illinois.edu/surveys'
    description: Test server
  - url: 'https://api-dev.rokwire.illinois.edu/surveys'
    description: Development server
  - url: 'http://localhost/surveys'
    description: Local server
tags:
  - name: Client
    description: Client applications APIs.
  - name: Admin
    description: Clients administration applications APIs.
  - name: BBs
    description: Building Block APIs.
  - name: TPS
    description: Third-Party Service APIs.
  - name: System
    description: Third-Party Service APIs.
  - name: Default
    description: Default APIs.
paths:  
  # Default
  /version:
    $ref: "./resources/default/version.yaml"

  # Client
  /api/surveys:
    $ref: "./resources/client/surveys.yaml"     
  /api/surveys/{id}:
    $ref: "./resources/client/surveysid.yaml"
  /api/surveys/{id}/responses:
    $ref: "./resources/client/surveysid-responses.yaml"
  /api/survey-responses:
    $ref: "./resources/client/survey-responses.yaml"     
  /api/survey-responses/{id}:
    $ref: "./resources/client/survey-responsesid.yaml"   
  /api/survey-alerts:
    $ref: "./resources/client/survey-alerts.yaml"
  /api/creator/surveys:
    $ref: "./resources/client/creator/surveys.yaml"
  /api/user-data:
    $ref: "./resources/client/user-data.yaml"  

  # Admin
  /api/admin/configs:
    $ref: "./resources/admin/configs.yaml"
  /api/admin/configs/{id}:
    $ref: "./resources/admin/configs-id.yaml"

  /api/admin/surveys:
    $ref: "./resources/admin/surveys.yaml"     
  /api/admin/surveys/{id}:
    $ref: "./resources/admin/surveysid.yaml"
  /api/admin/surveys/{id}/responses:
    $ref: "./resources/admin/surveysid-responses.yaml"
  /api/admin/alert-contacts:
    $ref: "./resources/admin/alert-contact.yaml"     
  /api/admin/alert-contacts/{id}:
    $ref: "./resources/admin/alert-contactids.yaml" 
  /api/admin/surveys/{id}/response:
    $ref: "./resources/admin/surveys_responses.yaml"  

  # Analytics
  /api/analytics/survey-responses:
    $ref: "./resources/analytics/survey-responses.yaml"  

  # BBs
  # /api/bbs/examples/{id}:
  #   $ref: "./resources/bbs/examples-id.yaml"
  
  # TPS
  # /api/tps/examples/{id}:
  #   $ref: "./resources/tps/examples-id.yaml"

  # System
    
components:
  securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  schemas:
    $ref: "./schemas/index.yaml"