// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BBs is an autogenerated mock type for the BBs type
type BBs struct {
	mock.Mock
}

// NewBBs creates a new instance of BBs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBBs(t interface {
	mock.TestingT
	Cleanup(func())
}) *BBs {
	mock := &BBs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
