// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConfigData is an autogenerated mock type for the ConfigData type
type ConfigData struct {
	mock.Mock
}

// NewConfigData creates a new instance of ConfigData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigData(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigData {
	mock := &ConfigData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
