// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	model "application/core/model"

	mock "github.com/stretchr/testify/mock"
)

// Notifications is an autogenerated mock type for the Notifications type
type Notifications struct {
	mock.Mock
}

// SendMail provides a mock function with given fields: toEmail, subject, body
func (_m *Notifications) SendMail(toEmail string, subject string, body string) {
	_m.Called(toEmail, subject, body)
}

// SendNotification provides a mock function with given fields: notification
func (_m *Notifications) SendNotification(notification model.NotificationMessage) {
	_m.Called(notification)
}

// NewNotifications creates a new instance of Notifications. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifications(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notifications {
	mock := &Notifications{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
