// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StorageListener is an autogenerated mock type for the StorageListener type
type StorageListener struct {
	mock.Mock
}

// OnConfigsUpdated provides a mock function with given fields:
func (_m *StorageListener) OnConfigsUpdated() {
	_m.Called()
}

// OnExamplesUpdated provides a mock function with given fields:
func (_m *StorageListener) OnExamplesUpdated() {
	_m.Called()
}

// NewStorageListener creates a new instance of StorageListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageListener {
	mock := &StorageListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
