// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TPS is an autogenerated mock type for the TPS type
type TPS struct {
	mock.Mock
}

// NewTPS creates a new instance of TPS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTPS(t interface {
	mock.TestingT
	Cleanup(func())
}) *TPS {
	mock := &TPS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
